barbershop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings
from barbershop.views import FrontpageView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', FrontpageView.as_view(), name='frontpage'),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^entry/', include('entry.urls', namespace='entry')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        })
    ]

entry/urls.py
from django.conf.urls import url
from .views import EntryView

urlpatterns = [
	url(r'^$', EntryView.as_view(), name='entry_form')
]

reviews/urls.py
from django.conf.urls import url
from .views import ReviewsListView, AddReviewView

urlpatterns = [
	url(r'^$', ReviewsListView.as_view(), name='reviews_list'),
	url(r'^add/$', AddReviewView.as_view(), name='add_review'),
]

reviews/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.conf import settings
import os
import math
from PIL import Image


class Review(models.Model):
    name = models.CharField(verbose_name=u'Имя', max_length=100)
    description = models.TextField(verbose_name=u'Описание', max_length=250)
    date_created = models.DateTimeField(verbose_name=u'Дата создания', auto_now_add=True)
    date_updated = models.DateTimeField(verbose_name=u'дата обновления', auto_now=True)

    is_haircut = models.BooleanField(verbose_name=u'стрижка', default=False)
    is_shave = models.BooleanField(verbose_name=u'бритье', default=False)
    is_moustache = models.BooleanField(verbose_name=u'усы', default=False)
    is_best_month_job = models.BooleanField(verbose_name=u'работа месяца', default=False)

    class Meta:
        verbose_name = u'Отзыв'
        verbose_name_plural = u'Отзывы'
        ordering = ['date_created']

    def __unicode__(self):
        return self.name


class ReviewPhoto(models.Model):
    image = models.ImageField(verbose_name=u'фото', upload_to='reviews')
    is_main = models.BooleanField(verbose_name=u'главное фото', default=False)
    review = models.ForeignKey(Review, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.image.path

    def base_resize(self, width, height, suffix='--resize', crop=True):
        full_path = settings.BASE_DIR + self.image.url
        image_url = os.path.dirname(self.image.url)
        image_name, image_ext = os.path.splitext(
            os.path.basename(full_path)
        )
        image_dir = os.path.dirname(full_path)

        resize_path = image_dir + '/' + image_name + suffix + image_ext
        resize_url = image_url + '/' + image_name + suffix + image_ext

        im = Image.open(full_path)
        width_ratio = float(width) / float(im.size[0])
        height_ratio = float(height) / float(im.size[1])
        ratio = max(width_ratio, height_ratio)
        size = (int(math.ceil(im.size[0] * ratio)), int(math.ceil(im.size[1] * ratio)))

        if crop:
            x = int(abs(size[0] - width)/2)
            y = int(abs(size[1] - height)/2)

            box = (x, y, size[0]-x, size[1]-y)
            im = im.resize(size, Image.ANTIALIAS).crop(box)
        else:
            im = im.resize(size, Image.ANTIALIAS)

        im.save(resize_path)

        return resize_url

    @property
    def resize_480x480(self):
        return self.base_resize(480, 480, suffix='--main')

    @property
    def resize_289x289(self):
        return self.base_resize(289, 289, suffix='--secondary')

    @property
    def resize_249x160(self):
        return self.base_resize(249, 160, suffix='--fp_desc')

    @property
    def resize_80x80(self):
        return self.base_resize(80, 80, suffix='--fp_tabl')

    @property
    def resize_50x50(self):
        return self.base_resize(50, 50, suffix='--fp_mobile')

reviews/forms.py
# -*- coding: utf-8 -*-
import os
from django import forms
from django.core import validators
from django.core.exceptions import ValidationError
from django.core.validators import get_available_image_extensions


class ClearableMultiFileInput(forms.ClearableFileInput):
	# override widget method in order to get all files from ImageField
	def value_from_datadict(self, data, files, name):
		if files:
			return files.getlist(name)
		else:
			return []


class MultiFileExtensionValidator(validators.FileExtensionValidator):
	def __call__(self, value):
		# iterate and validate each file, instead of validating list
		for item in value:
			extension = os.path.splitext(item.name)[1][1:].lower()
			if self.allowed_extensions is not None and extension not in self.allowed_extensions:
				raise ValidationError(
					self.message,
					code=self.code,
					params={
						'extension': extension,
						'allowed_extensions': ', '.join(self.allowed_extensions)
					}
				)


validate_multi_image_file_extension = MultiFileExtensionValidator(
	allowed_extensions=get_available_image_extensions(),
)


class MultiImageField(forms.ImageField):
	default_validators = [validate_multi_image_file_extension]

	def to_python(self, data):
		data_list = []
		# iterate and passed through every file instead of list
		for item in data:
			f = super(MultiImageField, self).to_python(item)
			data_list.append(f)
		return data_list


class AddReviewForm(forms.Form):
	name = forms.CharField(label='Ваше имя',
	                       widget=forms.TextInput(attrs={
		                       'class': 'text-field add-review__text-field',
		                       'placeholder': 'Имя'
	                       }))
	description = forms.CharField(label='Текст отзыва',
	                              widget=forms.Textarea(attrs={
		                              'class': 'text-field add-review__text-field',
		                              'placeholder': 'Текст отзыва'
	                              }))
	images = MultiImageField(required=False,
	                         widget=ClearableMultiFileInput(attrs={'multiple': True}))
	is_haircut = forms.BooleanField(label='Стрижка', required=False)
	is_shave = forms.BooleanField(label='Бритье', required=False)
	is_moustache = forms.BooleanField(label='Усы', required=False)

reviews/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import TemplateView, FormView
from django.urls import reverse_lazy, reverse
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned
from .models import Review, ReviewPhoto
from .forms import AddReviewForm
from price_list.models import PriceList


class ReviewsListView(TemplateView):
    def get(self, request, *args, **kwargs):
        template_name = 'reviews/reviews_list.html'
        try:
            reviews = Review.objects.all()
        except ObjectDoesNotExist:
            reviews = []
        try:
            price = PriceList.objects.get(version=True)
        except ObjectDoesNotExist:
            print(u'Ни один из прайсов не имеет отметки \'отображать на сайте\'')
            try:
                price = PriceList.objects.all().first()
            except ObjectDoesNotExist:
                print(u'В системе управления отсутствуют прайсы')
        except MultipleObjectsReturned:
            print(u'Несколько прайсов имеют отметку \'отображать на сайте\'')
            price = PriceList.objects.all().first()


        context = {
            'reviews': reviews,
            'price': price,
        }

        return render(request, template_name, context)


class AddReviewView(FormView):
    form_class = AddReviewForm
    template_name = 'reviews/add_review.html'
    success_url = '/reviews/'

    def get(self, request, *args, **kwargs):
        form = AddReviewForm()
        try:
            price = PriceList.objects.get(version=True)
        except ObjectDoesNotExist:
            print('Ни один из прайсов не имеет отметки \'отображать на сайте\'')
            try:
                price = PriceList.objects.all().first()
            except ObjectDoesNotExist:
                print('В системе управления отсутствуют прайсы')
        except MultipleObjectsReturned:
            print('Несколько прайсов имеют отметку \'отображать на сайте\'')
            price = PriceList.objects.all().first()

        context = {
            'form': form,
            'price': price,
        }

        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        form = AddReviewForm(request.POST, request.FILES)
        if form.is_valid():
            name = form.cleaned_data['name']
            description = form.cleaned_data['description']
            is_haircut = form.cleaned_data['is_haircut']
            is_shave = form.cleaned_data['is_shave']
            is_moustache = form.cleaned_data['is_moustache']

            review = Review.objects.create(name=name, description=description, is_haircut=is_haircut, is_shave=is_shave, is_moustache=is_moustache)

            review.save()

            for image in form.cleaned_data['images']:
                review_photo = ReviewPhoto.objects.create(image=image, review=review)
                review_photo.save()

            return HttpResponseRedirect(self.get_success_url())
        else:
            return render(request, self.template_name, {'form': form})

reviews/templates/reviews/add_review.html
{% extends 'reviews/reviews_list.html' %}

{% block reviews_content %}
	<section class="add-review">
		<div class="wrapper-layout-center add-review__wrapper">
			<form action="{% url 'reviews:add_review' %}" method="POST", enctype="multipart/form-data" class="add-review__form">
				{% csrf_token %}
				<div class="add-review__left-wr">
						{{ form.name }}
						{{ form.description }}
				</div>
				<div class="add-review__right-wr">
					<label for="{{ form.is_haircut.id_for_label }}" class="checkbox">
						{{ form.is_haircut }}
						<span class="visible-checkbox"></span>
						Стрижка
					</label>
					<label for="{{ form.is_shave.id_for_label }}" class="checkbox">
						{{ form.is_shave }}
						<span class="visible-checkbox"></span>
						Бритье
					</label>
					<label for="{{ form.is_moustache.id_for_label }}" class="checkbox">
						{{ form.is_moustache }}
						<span class="visible-checkbox"></span>
						Усы
					</label>
					<label for="{{ form.images.id_for_label }}" class="upload">
						Вы можете прикрепить изоюражения к Вашему отзыву
						{{ form.images }}
					</label>
					<button type="submit" class="btn add-review__submit">Добавить отзыв</button>
				</div>
			</form>
		</div>
	</section>

{% endblock reviews_content %}

reviews/templates/reviews/reviews_list.html
{% extends 'base.html' %}
{% load static %}

{% block page_title %}
	Наши работы - barbershop
{% endblock %}

{% block main %}
	{% block reviews_content %}
		<section class="examples">
			<div class="wrapper-layout-center examples__wrapper">
				<h1 class="examples__title">Наши работы</h1>
				<a href="/reviews/add/" class="btn examples__on-the-main">
					Добавить отзыв
				</a>

				{% for review in reviews %}
					<div class="example examples__item
								{% if review.is_best_month_job %} example_main {% endif %}">
						<picture>
							<source media="(min-width: 1200px)"
							        srcset="
							        {% if review.is_best_month_job %}
							            {{ review.reviewphoto_set.all.0.resize_480x480 }}
									{% else %}
										{{ review.reviewphoto_set.all.0.resize_289x289 }}
									{% endif %}">
							<source media="(min-width: 768px)"
							        srcset="">
							<img class="example__photo" src=""
							     alt='{{ review.name }}'>
						</picture>
						<div class="example__description">
							<b class="example__name">{{ review.name }}</b>
							<p class="example__feedback">{{ review.description }}</p>
							<ul class="example__service-list">
								{% if review.is_haircut %}
									<li class="example__service-item example__service-item_haircut">
										Стрижка
									</li>
								{% endif %}
								{% if review.is_shave %}
									<li class="example__service-item example__service-item_shave">
										Бритье
									</li>
								{% endif %}
								{% if review.is_moustache %}
									<li class="example__service-item example__service-item_mustache">
										Усы
									</li>
								{% endif %}
							</ul>
						</div>
					</div>
				{% empty %}
					<p class="empty-text">В данном разделе пока нет отзывов</p>
				{% endfor %}

			</div>
		</section>
	{% endblock reviews_content %}

	{% block price %}
		{% include 'price_list/price_list.html' %}
	{% endblock price %}
{% endblock main %}