barbershop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings
from barbershop.views import FrontpageView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', FrontpageView.as_view(), name='frontpage'),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^entry/', include('entry.urls', namespace='entry')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        })
    ]

entry/urls.py
from django.conf.urls import url
from .views import EntryView

urlpatterns = [
	url(r'^$', EntryView.as_view(), name='entry_form')
]

price_list/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.exceptions import ObjectDoesNotExist


class PriceList(models.Model):
	title = models.CharField(verbose_name='Заголовок', max_length=100)
	version = models.BooleanField(verbose_name='Отображать на сайте', default=False)
	special_offers = models.CharField(verbose_name='Акции', max_length=200)

	class Meta:
		verbose_name = 'Прайс'
		verbose_name_plural = 'Прайсы'

	def __str__(self):
		return self.title

	def save(self, force_insert=False, force_update=False, using=None, update_fields=None):
		if self.version:
			try:
				tmp = PriceList.objects.get(version=True)
				if tmp != self:
					tmp.version = False
					tmp.save()
			except ObjectDoesNotExist:
				pass
		super(PriceList, self).save(force_insert=False, force_update=False, using=None, update_fields=None)


class PriceItem(models.Model):
	price_list = models.ForeignKey(PriceList, on_delete=models.CASCADE)
	service = models.CharField(verbose_name='Название услуги', max_length=150)

	ADD_SERVICES = (
		('0', '(с мытьем головы)'),
		('1', '(без мытья)'),
	)

	head_clean = models.CharField(max_length=200, choices=ADD_SERVICES)
	Price = models.PositiveIntegerField()

	def __str__(self):
		return self.service

price_list/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

# Create your views here.

price_list/templates/price_list/price_list.html
{% load static %}

{% if price %}
<section class="price">
	<div class="wrapper-layout-center price__wrapper">
		<h2 class="price__title">{{ price.title }}</h2>
		<table class="price__list">
			{% for item in price.priceitem_set.all %}
				<tr>
					<td class="price__first-col">{{ forloop.counter }}</td>
					<td class="price__second-col">{{ item.service }}</td>
					<td class="price__third-col">{{ item.get_head_clean_display }}</td>
					<td class="price__value">{{ item.Price }} руб.</td>
				</tr>
			{% endfor %}
		</table>
		<div class="price__discounts">
			<picture>
				<source media="(min-width: 1200px)"
				        srcset="{% static 'img/clock-desktop.png' %}">
				<img class="price__clock" src="{% static 'img/clock.png' %}" alt="часы">
			</picture>
			<span>{{ price.special_offers }}</span>
		</div>
	</div>
</section>
{% endif %}