accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views as acc_views


urlpatterns = [
    url(r'^registration/$', acc_views.AccountsRegistrationView.as_view(), name='registration'),
    url(r'^profile/$', acc_views.AccountsProfileView.as_view(), name='profile'),

    url(r'^login/$', acc_views.AccountsLoginView.as_view(), name='login'),
    url(r'^logout/$', acc_views.AccountsLogoutView.as_view(), name='logout'),

    #url(r'^password_change/$', acc_views.AccountsPasswordChangeView.as_view(), name='password_change'),
    url(r'^password_change/done/$', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    url(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
    url(r'^password_reset/done/$', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

barbershop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings
from barbershop.views import FrontpageView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', FrontpageView.as_view(), name='frontpage'),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^entry/', include('entry.urls', namespace='entry')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        })
    ]

entry/urls.py
from django.conf.urls import url
from .views import EntryView

urlpatterns = [
	url(r'^$', EntryView.as_view(), name='entry_form')
]

accounts/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.db.models import signals
from django.contrib.auth.models import User
from django.conf import settings
import os
from PIL import Image
import math


class Account(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(blank=True, null=True)
    avatar = models.ImageField(upload_to='avatars')

    class Meta:
        verbose_name = 'Аккаунт'
        verbose_name_plural = 'Аккаунты'

    def __str__(self):
        return self.user.username

    def base_resize(self, width, height, suffix='--resize', crop=True):
        full_path = settings.BASE_DIR + self.avatar.url
        image_url = os.path.dirname(self.avatar.url)
        image_name, image_ext = os.path.splitext(
            os.path.basename(full_path)
        )
        image_dir = os.path.dirname(full_path)

        resize_path = image_dir + '/' + image_name + suffix + image_ext
        resize_url = image_url + '/' + image_name + suffix + image_ext

        im = Image.open(full_path)

        width_ratio = float(width)/float(im.size[0])
        height_ratio = float(height)/float(im.size[1])

        ratio = max(width_ratio, height_ratio)
        size = (int(math.ceil(im.size[0]*ratio)), int(math.ceil(im.size[1]*ratio)))

        if crop:
            x = int(abs(size[0] - width)/2)
            y = int(abs(size[1] - height)/2)

            box = (x, y, size[0]-x, size[1]-y)
            im = im.resize(size, Image.ANTIALIAS).crop(box)
        else:
            im = im.resize(size, Image.ANTIALIAS)

        im.save(resize_path)

        return resize_url

    @property
    def resize_200x200(self):
        return self.base_resize(200, 200, suffix='--avatar')

accounts/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth import forms as auth_forms, password_validation
from django import forms
from django.forms import widgets

from django.utils.translation import ugettext, ugettext_lazy as _


class AccountsRegistrationForm(forms.Form):
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(AccountsRegistrationForm, self).__init__(*args, **kwargs)

    username = forms.CharField()
    password = forms.CharField(widget=widgets.PasswordInput())
    password2 = forms.CharField(widget=widgets.PasswordInput())
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField()

    age = forms.IntegerField(required=False)
    avatar = forms.ImageField(required=False)

    def clean_password2(self):
        password = self.cleaned_data.get("password")
        password2 = self.cleaned_data.get("password2")
        if password and password2 and password != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code='password_mismatch',
            )
        self.user.username = self.cleaned_data.get('username')
        password_validation.validate_password(self.cleaned_data.get('password2'), self.user)
        return password2


class AccountsChangeForm(forms.Form):
    def __init__(self, user=None, *args, **kwargs):
        self.user = user
        super(AccountsChangeForm, self).__init__(*args, **kwargs)


    username = forms.CharField()
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField()

    age = forms.IntegerField(required=False)
    avatar = forms.ImageField(required=False)


class AccountsAuthenticationForm(auth_forms.AuthenticationForm):
    username = auth_forms.UsernameField(
        max_length=254,
        widget=widgets.TextInput(attrs={
            'autofocus': True,
            'class': 'text-field login-popup__login-field',
            'placeholder': 'Логин',
        }),
    )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'class': 'text-field login-popup__password-field',
            'placeholder': 'Пароль'
        }),
    )

    remember = forms.BooleanField(
        widget=widgets.CheckboxInput(attrs={
            'class': 'login-popup__ibvisible-checkbox'
        }),
        required=False,
    )

accounts/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from django.contrib.auth import views as auth_views, login
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import PasswordChangeForm
from django.views.generic import FormView, TemplateView

from .forms import (
    AccountsAuthenticationForm, AccountsRegistrationForm, AccountsChangeForm,
)
from .models import Account




class AccountsRegistrationView(FormView):
    template_name = 'accounts/registration.html'
    form_class = AccountsRegistrationForm
    success_url = '/accounts/profile/'

    def get(self, request, *args, **kwargs):
        form = AccountsRegistrationForm(request.user)
        if request.user.is_authenticated:
            return redirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form })

    def post(self, request, *args, **kwargs):
        form = AccountsRegistrationForm(request.user, request.POST, request.FILES)

        if form.is_valid():
            username = form.cleaned_data['username']
            first_name = form.cleaned_data['first_name']
            last_name = form.cleaned_data['last_name']
            age = form.cleaned_data['age']
            email = form.cleaned_data['email']
            avatar = request.FILES.get('avatar')

            user = User.objects.create(username=username, first_name=first_name, last_name=last_name, email=email)
            user.set_password(form.cleaned_data['password'])

            account = Account.objects.create(age=age, avatar=avatar, user=user)

            user.save()
            account.save()

            login(request, user)

            return redirect(self.success_url)
        else:
            return render(request, self.template_name, {'form': form })



class AccountsLoginView(auth_views.LoginView):
    template_name = 'accounts/login.html'
    form_class = AccountsAuthenticationForm
    success_url = '/accounts/profile/'

    def get(self, request, *args, **kwargs ):
        if request.user.is_authenticated:
            return redirect(self.success_url)
        else:
            form = self.get_form()
            return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.get_form()

        if form.is_valid():
            print('entered form.is_valid')
            self.form_valid(form)
            return redirect(self.success_url)
        else:
            print('form not valid')
            self.form_invalid(form)
            return render(request, self.template_name, {'form': form })


class AccountsLogoutView(auth_views.LogoutView):
    template_name = 'accounts/logged_out.html'


class AccountsProfileView(TemplateView, LoginRequiredMixin):
    template_name = 'accounts/profile.html'
    success_url = '/accounts/profile/'

    def get(self, request, *args, **kwargs):
        user = request.user
        if user.is_authenticated and hasattr(user, 'account'):
            form = AccountsChangeForm(
                initial = {
                    'username': user.username,
                    'first_name': user.first_name,
                    'last_name': user.last_name,
                    'email': user.email,
                    'age': user.account.age,
                }
            )
            form_password = PasswordChangeForm(user=user)
            context = {
                'user': user,
                'form': form,
                'form_password': form_password,
            }

            return render(request, self.template_name, context)
        else:
            return redirect('/accounts/login/')


    def post(self, request, *args, **kwargs):
        user = request.user
        form = AccountsChangeForm(request.user, request.POST, request.FILES)
        if form.is_valid():
            user.username = form.cleaned_data['username']
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.account.age = form.cleaned_data['age']
            user.email = form.cleaned_data['email']
            if request.FILES.get('avatar'):
                user.account.avatar = request.FILES.get('avatar')

            user.save()
            user.account.save()

            return redirect(self.success_url)
        else:
            context = {
                'user': user,
                'form': form,
            }
            return render(request, self.template_name, context)

accounts/templates/accounts/logged_out.html
{% extends 'base.html' %}

{% block main %}
<div class="wrapper-layout-center">
	<h1>Вы вышли из своего аккаунта</h1>
	<p></p>
	<a href="{% url 'accounts:login' %}">Войти в аккаунт</a>
</div>
{% endblock main %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block main %}
<div class="wrapper-layout-center">
	<form class="login-popup" action="{% url 'accounts:login' %}" method="POST">
		{% csrf_token %}
		<h2 class="login-popup__title">Личный кабинет</h2>
		<p class="login-popup__description">Введите свой лошин и пароль, чтобы войти</p>
		{{ form.username }}
		{{ form.username.errors }}
		{{ form.password }}
		{{ form.password.errors }}
		<label class="login-popup__remember-me">

			<span class="login-popup__visible-checkbox"></span>
				Запомните меня
		</label>
		<a class="login-popup__password-restore" href="#">Я забыл пароль!</a>
		<div class="login-popup__buttons">
			<button class="btn login-popup__submit" type="submit">
				Войти<span class="login-popup__submit-invis"> в личный кабинет</span>
			</button>
			<a class="login-popup__registration" href="/accounts/registration/">Зарегистрироваться
			</a>
		</div>
	</form>
</div>
{% endblock main %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block main %}

<div class="wrapper-layout-center">
	<section class="login-popup">
		<form action="{% url 'accounts:profile' %}" method="POST" enctype="multipart/form-data">
			{% csrf_token %}
			<h1 class="login-popup__title">Личный кабинет</h1>
			<h2>{{ user.username }}</h2>
			{{ form.errors }}
			{% for field in form %}
				<p>{{ field }}</p>
			{% endfor %}
			{% if user.account.avatar %}
				<img src="{{ user.account.resize_200x200 }}" alt="аватар">
			{% endif %}
			<button class="btn login-popup__submit" type="submit">Обновить</button>
		</form>

		<!--<form action="{% url 'accounts:password_change_done' %}" method="POST" enctype="">-->
			<!--{% csrf_token %}-->
			<!--<h2 class="login-popup__title">Изменить пароль</h2>-->
			<!--{{ form_password.errors }}-->
			<!--{% for field in form_password %}-->
				<!--<p>{{ field.label }}{{ field }}</p>-->
			<!--{% endfor %}-->
			<!--<button class="btn login-popup__submit" type="submit">Изменить пароль</button>-->
		<!--</form>-->

		<a href="{% url 'accounts:logout' %}">Выйти из аккаунта</a>

	</section>
</div>

{% endblock main %}

accounts/templates/accounts/registration.html
{% extends 'base.html' %}

{% block main %}
<div class="wrapper-layout-center">
	<form class="login-popup" action="{% url 'accounts:registration' %}" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<h2 class="login-popup__title">Регистрация</h2>
		{{ form }}
		{{ form.errors }}
		<button class="btn login-popup__submit" type="submit">Регистрация</button>
	</form>
</div>
{% endblock main %}