barbershop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.views.static import serve
from django.conf import settings
from barbershop.views import FrontpageView



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', FrontpageView.as_view(), name='frontpage'),
    url(r'^reviews/', include('reviews.urls', namespace='reviews')),
    url(r'^entry/', include('entry.urls', namespace='entry')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts'))
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT
        })
    ]

entry/urls.py
from django.conf.urls import url
from .views import EntryView

urlpatterns = [
	url(r'^$', EntryView.as_view(), name='entry_form')
]

entry/models.py
# -*- coding: utf-8 -*-
from django.db import models


class Entry(models.Model):
    last_name = models.CharField(max_length=100, verbose_name=u'Фамилия')
    first_name = models.CharField(max_length=100, verbose_name=u'Имя')
    second_name = models.CharField(max_length=100, verbose_name=u'Отчество', blank=True)
    tel_number = models.CharField(max_length=100, verbose_name=u'Контактный телефон', blank=True)
    email = models.EmailField(max_length=100, verbose_name=u'Контактный e-mail')
    add_info = models.TextField(max_length=200, verbose_name=u'доп. информация')

    BEARD_MODELS = (
        ('admiral', u'адмирал'),
        ('woodchoper', u'лесоруб'),
        ('polar', u'полярник'),
        ('merchant', u'боярин'),
        ('elder', u'мудрец'),
    )

    beard_model = models.CharField(max_length=100, verbose_name=u'модель бороды',
                                   choices=BEARD_MODELS)

    is_beard_paint = models.BooleanField(default=False, verbose_name=u'Подкрасить бороду')
    is_beard_brush = models.BooleanField(default=False, verbose_name=u'Причесать бороду')
    is_remove_gray = models.BooleanField(default=False, verbose_name=u'Убрать седину')
    is_moustache_spin = models.BooleanField(default=False, verbose_name=u'Накрутить усы')
    is_trim = models.BooleanField(default=False, verbose_name=u'Подровнять виски')
    is_polish_head = models.BooleanField(default=False, verbose_name=u'отполировать лысину')

    date_added = models.DateTimeField(verbose_name=u'дата и время создания', auto_now_add=True)
    date_record = models.DateTimeField(verbose_name=u'дата и время записи')

    class Meta:
        verbose_name = u'запись на прием'
        verbose_name_plural = u'записи на прием'
        ordering = ['-date_record']

    def __unicode__(self):
        return self.get_full_name()

    def get_full_name(self):
        return self.last_name + ' ' + self.first_name

entry/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import widgets
from django.forms.utils import ErrorList
from .models import Entry


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        exclude = ['date_added']
        widgets = {
            'last_name': widgets.TextInput(attrs={
                'class': 'appointment__text-field text-field',
                'placeholder': u'Фамилия'
            }),
            'first_name': widgets.TextInput(attrs={
                'class': 'appointment__text-field text-field',
                'placeholder': u'Имя'
            }),
            'second_name': widgets.TextInput(attrs={
                'class': 'appointment__text-field text-field',
                'placeholder': u'Отчество'
            }),
            'tel_number': widgets.TextInput(attrs={
                'class': 'appointment__text-field text-field',
                'placeholder': u'Контактный телефон'
            }),
            'email': widgets.TextInput(attrs={
                'class': 'appointment__text-field text-field',
                'placeholder': u'Контактный email'
            }),
            'add_info': widgets.Textarea(attrs={
                'class': 'text-field appointment__add-info',
                'placeholder': u'Допю информация для мастера'
            }),
            'beard_model': widgets.RadioSelect(attrs={
                'class': 'invisible-radiobox'
            }),
            'is_beard_paint': widgets.CheckboxInput(attrs={
                'class': 'invisible-checkbox'
            }),
            'is_beard_brush': widgets.CheckboxInput(attrs={
                'class': 'invisible-checkbox'
            }),
            'is_remove_gray': widgets.CheckboxInput(attrs={
                'class': 'invisible-checkbox'
            }),
            'is_moustache_spin': widgets.CheckboxInput(attrs={
                'class': 'invisible-checkbox'
            }),
            'is_trim': widgets.CheckboxInput(attrs={
                'class': 'invisible-checkbox'
            }),
            'is_polish_head': widgets.CheckboxInput(attrs={
                'class': 'invisible-checkbox'
            }),
            'date_record': widgets.DateTimeInput(attrs={
                'class': 'appointment__text-field text-field',
                'placeholder': u'Дата и время записи в формате гггг-мм-дд чч:мм'
            }),
        }

entry/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import TemplateView, FormView
from .forms import EntryForm


class EntryView(FormView):
    template_name = 'entry/entry.html'

    def get(self, request, *args, **kwargs):
        form = EntryForm()
        return render(request, self.template_name, {'form': form })

    def post(self, request, *args, **kwargs):
        form = EntryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/')
        else:
            return render(request, self.template_name, {'form': form })

entry/templates/entry/entry.html
{% extends 'base.html' %}

{% block page_title %}
	Запимь на прием - barbershop
{% endblock %}

{% block main %}
	<form action="{% url 'entry:entry_form' %}" method="POST" class="appointment" novalidate>
		{% csrf_token %}
		<div class="wrapper-layout-center appointment__wrapper">
			<h1 class="appointment__title">Запись на стрижку</h1>
			<a href="/" class="btn appointment__on-the-main" type="button">На главную</a>

			<div class="appointment__full-name">
				<label for="{{ form.last_name.id_for_label }}"
				       class="{% if form.last_name.errors %} error{% endif %}">
					{{ form.last_name }}
					{{ form.last_name.errors }}
				</label>
				<label for="{{ form.first_name.id_for_label }}"
				       class="{% if form.first_name.errors %} error{% endif %}">
					{{ form.first_name }}
					{{ form.first_name.errors }}
				</label>
				<label for="{{ form.second_name.id_for_label }}"
				       class="{% if form.second_name.errors %} error{% endif %}">
					{{ form.second_name }}
					{{ form.second_name.errors }}
				</label>
			</div>

			<div class="appointment__date">
				<label for="{{ form.date_record.id_for_label }}"
					       class="{% if form.date_record.errors %} error{% endif %}">
					{{ form.date_record }}
					{{ form.date_record.errors }}
				</label>
			</div>

			<div class="appointment__contacts">
				<label for="{{ form.tel_number.id_for_label }}"
				       class="{% if form.tel_number.errors %} error{% endif %}">
					{{ form.tel_number }}
					{{ form.tel_number.errors }}
				</label>
				<label for="{{ form.email.id_for_label }}"
				       class="{% if form.email.errors %} error{% endif %}">
					{{ form.email }}
					{{ form.email.errors }}
				</label>
			</div>

			<label for="{{ form.add_info.id_for_label }}"
				       class="{% if form.add_info.errors %} error{% endif %}">
				{{ form.add_info }}
				{{ form.add_info.errors }}
			</label>

			<div class="appointment__beard">
				<legend class="appointment__beard-title"><span>Выберите модель бороды:</span></legend>
				{% for radiobox in form.beard_model|slice:"1:" %}
					<label class="appointment__beard-type appointment__beard-type_{{ forloop.counter0 }}">
						{{ radiobox.tag }}
						{{ radiobox.choice_label }}
						<span class="visible-radiobox"></span>
					</label>
				{% endfor %}
				{{ form.beard_model.errors }}
			</div>

			<div class="appointment__add-srvices">
				<legend class="appointment__add-srvices-title"><span>Дополнительные услуги:</span></legend>
				<label class="appointment__add-service">
					{{ form.is_beard_paint }}
					<span class="visible-checkbox"></span>
					{{ form.is_beard_paint.label }}
					{{ form.is_beard_paint.errors }}
				</label>
				<label class="appointment__add-service">
					{{ form.is_moustache_spin }}
					<span class="visible-checkbox"></span>
					{{ form.is_moustache_spin.label }}
					{{ form.is_moustache_spin.errors }}
				</label>
				<label class="appointment__add-service">
					{{ form.is_beard_brush }}
					<span class="visible-checkbox"></span>
					{{ form.is_beard_brush.label }}
					{{ form.is_beard_brush.errors }}
				</label>
				<label class="appointment__add-service">
					{{ form.is_trim }}
					<span class="visible-checkbox"></span>
					{{ form.is_trim.label }}
					{{ form.is_trim.errors }}
				</label>
				<label class="appointment__add-service">
					{{ form.is_remove_gray }}
					<span class="visible-checkbox"></span>
					{{ form.is_remove_gray.label }}
					{{ form.is_remove_gray.errors }}
				</label>
				<label class="appointment__add-service">
					{{ form.is_polish_head }}
					<span class="visible-checkbox"></span>
					{{ form.is_polish_head.label }}
					{{ form.is_polish_head.errors }}
				</label>
			</div>
			<button type="submit" class="btn appointment__submit">Отправить заявку</button>
		</div>
	</form>

{% endblock main %}